{{- $generatedNamespace := include "agentNamespace" . }}
{{- if ne $generatedNamespace .Release.Namespace }}
{{- if or .Values.bootstrapHubKubeConfig .Values.externalManagedKubeConfig .Values.multiHubBootstrapHubKubeConfigs }}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    workload.openshift.io/allowed: "management"
  labels:
    gwcp.guidewire.com/app-name: cluster-manager
    gwcp.guidewire.com/created-by: pod-vulcan
    gwcp.guidewire.com/dept: "275"
    gwcp.guidewire.com/maintained-by: pod-vulcan
    gwcp.guidewire.com/tenant-name: quadrant-shared
    gwcp.guidewire.com/version: 0.16.0
  name: "{{ template "agentNamespace" . }}"
{{- end }}
{{- end }}
