{{- if .Values.externalManagedKubeConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: external-managed-kubeconfig
  namespace: "{{ template "agentNamespace" . }}"
  labels:
    gwcp.guidewire.com/app-name: cluster-manager
    gwcp.guidewire.com/created-by: pod-vulcan
    gwcp.guidewire.com/dept: "275"
    gwcp.guidewire.com/maintained-by: pod-vulcan
    gwcp.guidewire.com/tenant-name: quadrant-shared
    gwcp.guidewire.com/version: 0.16.0
type: Opaque
data:
  kubeconfig: {{ .Values.externalManagedKubeConfig | b64enc }}
{{- end }}
