{{- if .Values.klusterlet.create }}
apiVersion: operator.open-cluster-management.io/v1
kind: Klusterlet
metadata:
  name: "{{ template "klusterletName" . }}"
  labels:
    gwcp.guidewire.com/app-name: cluster-manager
    gwcp.guidewire.com/created-by: pod-vulcan
    gwcp.guidewire.com/dept: "275"
    gwcp.guidewire.com/maintained-by: pod-vulcan
    gwcp.guidewire.com/tenant-name: quadrant-shared
    gwcp.guidewire.com/version: 0.16.0
spec:
  deployOption:
    mode: {{ .Values.klusterlet.mode | default "Singleton" }}
  registrationImagePullSpec: "{{ template "registrationImage" . }}"
  workImagePullSpec: "{{ template "workImage" . }}"
  imagePullSpec: "{{ template "operatorImage" . }}"
  clusterName: "{{ .Values.klusterlet.clusterName }}"
  namespace: "{{ template "klusterletNamespace" . }}"
  {{- with .Values.klusterlet.externalServerURLs }}
  externalServerURLs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.klusterlet.resourceRequirement }}
  resourceRequirement:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.klusterlet.nodePlacement }}
  nodePlacement:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.klusterlet.registrationConfiguration }}
  registrationConfiguration:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.klusterlet.workConfiguration }}
  workConfiguration:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.priorityClassName }}
  priorityClassName: "{{ .Values.priorityClassName }}"
  {{- end }}
{{- end }}
