{{- if or ( eq .Values.klusterlet.mode "Singleton") (eq .Values.klusterlet.mode "Default") }}
{{- if not .Values.noOperator }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: klusterlet
  namespace: {{ .Release.Namespace }}
  labels:
    gwcp.guidewire.com/app-name: cluster-manager
    gwcp.guidewire.com/created-by: pod-vulcan
    gwcp.guidewire.com/dept: "275"
    gwcp.guidewire.com/maintained-by: pod-vulcan
    gwcp.guidewire.com/tenant-name: quadrant-shared
    gwcp.guidewire.com/version: 0.16.0
imagePullSecrets:
  - name: open-cluster-management-image-pull-credentials
{{- end }}
{{- end }}
