apiVersion: v1
kind: Service
metadata:
  name: cluster-manager-registration-webhook
  namespace: {{ .ClusterManagerNamespace }}
  labels:
    {{ if .Labels }}
    {{ range $element := split "," .Labels }}
    {{ $kv := splitn $element "=" 2 }}
    {{- if eq (len $kv) 2 }}
    {{ index $kv 0 }}: {{ index $kv 1 }}
    {{- end }}
    {{ end }}
    {{ end }}
spec:
  selector:
    app: {{ .ClusterManagerName }}-registration-webhook
  ports:
  - name: webhook
    port: 9443
    targetPort: 9443
