kind: Endpoints
apiVersion: v1
metadata:
  name: cluster-manager-registration-webhook
  namespace: {{ .ClusterManagerNamespace }}
  labels:
    {{ if .Labels }}
    {{ range $pair := split .Labels "," }}
      {{ $kv := splitn $pair "=" 2 }}
      {{ if eq (len $kv) 2 }}
    {{ index $kv 0 }}: {{ index $kv 1 }}
      {{ end }}
    {{ end }}
    {{ end }}
subsets:
  - addresses:
      - ip: {{.RegistrationWebhook.Address}}
    ports:
      - port: {{.RegistrationWebhook.Port}}
        name: tls
