apiVersion: v1
kind: ServiceAccount
metadata:
  name: registration-controller-sa
  namespace: {{ .ClusterManagerNamespace }}
  {{with ManagedClusterIdentityCreatorRole}}
  annotations:
    eks.amazonaws.com/role-arn: {{ ManagedClusterIdentityCreatorRole }}
  {{end}}