apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:{{ .ClusterManagerName }}-placement:controller
  labels:
    {{ if .Labels }}
    {{ range $pair := split .Labels "," }}
      {{ $kv := splitn $pair "=" 2 }}
      {{ if eq (len $kv) 2 }}
    {{ index $kv 0 }}: {{ index $kv 1 }}
      {{ end }}
    {{ end }}
    {{ end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:{{ .ClusterManagerName }}-placement:controller
subjects:
- kind: ServiceAccount
  namespace: {{ .ClusterManagerNamespace }}
  name: placement-controller-sa
